<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>RestaurantOrderManager.Backend</RootNamespace>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
      <UserSecretsId>26b9618a-2805-4ad1-b14d-2819b852dabd</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
        <PackageReference Include="Grpc.AspNetCore.Web" Version="2.71.0" />
        <PackageReference Include="Makaretu.Dns.Multicast.New" Version="0.38.0" />
        <PackageReference Include="RestaurantOrderManager.Backend.Proto" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Resources\menu.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

  </Project>
